-- SmartMatch Phase 1: live Match Engine RPC
create unique index if not exists matches_request_tutor_uidx
on public.matches(request_id, tutor_id);

alter table public.matches drop constraint if exists matches_request_tutor_key;
drop index if exists matches_request_tutor_uidx;
alter table public.matches add constraint matches_request_tutor_key unique (request_id,tutor_id);

create or replace function public.generate_matches(p_request_id uuid)
returns table(id uuid,request_id uuid,tutor_id uuid,match_score numeric,score_breakdown jsonb,status public.match_status)
language plpgsql volatile set search_path=public
as $$
declare r public.parent_requests%rowtype;
begin
 if not public.is_admin() then raise exception 'Admin access required'; end if;
 select * into r from public.parent_requests where public.parent_requests.id=p_request_id;
 if not found then raise exception 'Request not found'; end if;
 with base as (
  select t.id as tutor_id,t.subjects,t.levels,t.lesson_formats,t.locations,t.hourly_rate,t.availability,
         regexp_match(coalesce(r.budget,''),'([0-9]+(?:\.[0-9]+)?)(?:[^0-9]+([0-9]+(?:\.[0-9]+)?))?') as budget_parts
  from public.tutors t
  where t.status in ('verified','active')
   and exists(select 1 from unnest(t.subjects) s where regexp_replace(replace(replace(lower(trim(s)),'mathematics','math'),'maths','math'),'\s+',' ','g')=regexp_replace(replace(replace(lower(trim(r.subject)),'mathematics','math'),'maths','math'),'\s+',' ','g'))
   and exists(select 1 from unnest(t.levels) l where lower(trim(l))=lower(trim(r.student_level)) or lower(trim(l)) like '%'||split_part(lower(trim(r.student_level)),' ',1)||'%')
   and (lower(coalesce(r.lesson_format,'')) not like '%home%' or exists(select 1 from unnest(t.locations) l where lower(l) like '%'||lower(coalesce(r.location,''))||'%' or lower(l) like '%islandwide%'))
   and (coalesce(lower(r.lesson_format),'')='' or lower(r.lesson_format) like '%either%' or exists(select 1 from unnest(t.lesson_formats) f where lower(f) like '%'||lower(r.lesson_format)||'%' or lower(f) like '%either%'))
 ),scored as (
  select b.*,
   case when exists(select 1 from unnest(b.subjects) s where regexp_replace(replace(replace(lower(trim(s)),'mathematics','math'),'maths','math'),'\s+',' ','g')=regexp_replace(replace(replace(lower(trim(r.subject)),'mathematics','math'),'maths','math'),'\s+',' ','g')) then 30 else 0 end subject_score,
   case when exists(select 1 from unnest(b.levels) l where lower(trim(l))=lower(trim(r.student_level))) then 20 when exists(select 1 from unnest(b.levels) l where lower(trim(l)) like '%'||split_part(lower(trim(r.student_level)),' ',1)||'%') then 12 else 0 end level_score,
   case when lower(coalesce(r.lesson_format,'')) like '%online%' or lower(coalesce(r.lesson_format,'')) like '%either%' then 15 when exists(select 1 from unnest(b.locations) l where lower(l) like '%'||lower(coalesce(r.location,''))||'%' or lower(l) like '%islandwide%') then 15 else 0 end location_score,
   case when coalesce(lower(r.lesson_format),'')='' or lower(r.lesson_format) like '%either%' then 10 when exists(select 1 from unnest(b.lesson_formats) f where lower(f) like '%'||lower(r.lesson_format)||'%' or lower(f) like '%either%') then 10 else 0 end format_score,
   case when b.hourly_rate is null then 5 when b.budget_parts[2] is not null and b.hourly_rate between b.budget_parts[1]::numeric and b.budget_parts[2]::numeric then 10 when b.budget_parts[1] is not null and abs(b.hourly_rate-b.budget_parts[1]::numeric)<=10 then 7 else 0 end budget_score,
   case when coalesce(trim(r.preferred_schedule),'')='' or coalesce(trim(b.availability),'')='' then 7.5 when lower(b.availability) like '%'||lower(trim(r.preferred_schedule))||'%' then 15 when exists(select 1 from regexp_split_to_table(lower(r.preferred_schedule),'[^a-z]+') token where token in ('monday','tuesday','wednesday','thursday','friday','saturday','sunday') and lower(b.availability) like '%'||token||'%') then 8 else 0 end availability_score
  from base b
 ),ranked as (
  select s.*,least(100,s.subject_score+s.level_score+s.location_score+s.format_score+s.budget_score+s.availability_score)::numeric total_score,
    jsonb_build_object('subject',s.subject_score,'level',s.level_score,'location',s.location_score,'format',s.format_score,'budget',s.budget_score,'availability',s.availability_score) breakdown
  from scored s where s.subject_score=30 and s.level_score>0
  order by s.subject_score+s.level_score+s.location_score+s.format_score+s.budget_score+s.availability_score desc,s.tutor_id limit 10
 )
 insert into public.matches(request_id,tutor_id,match_score,score_breakdown,notes,status)
 select p_request_id,ranked.tutor_id,ranked.total_score,ranked.breakdown,'Generated by SmartMatch Match Engine','shortlisted'::public.match_status
 from ranked where ranked.total_score>=50
 on conflict on constraint matches_request_tutor_key do update
 set match_score=excluded.match_score,score_breakdown=excluded.score_breakdown,notes=excluded.notes
 where public.matches.status not in ('accepted','trial','confirmed','closed');
 if r.status not in ('trial','confirmed','closed') then update public.parent_requests pr set status='matching' where pr.id=p_request_id; end if;
 return query select m.id,m.request_id,m.tutor_id,m.match_score,m.score_breakdown,m.status from public.matches m where m.request_id=p_request_id order by m.match_score desc;
end;
$$;

revoke all on function public.generate_matches(uuid) from public,anon,authenticated;
grant execute on function public.generate_matches(uuid) to authenticated;
